# Learning ML with OHE

### How to generate and train sparese features
* Generate categorical sparse features with DictVectorizer with Sparse
* Encode the non-categorical features as sparse matrix.
* Add sparse matrix non-categorical to sparse matrix of categorical features (find horizontal add).
* Train model using sparse matrix

Solution for concat is [here](http://stackoverflow.com/questions/16879313/how-to-concatenate-two-matrices-in-python). Need a horizontal add version not vertical.

You can actually do regular index access of sparse matrix (e.g. df_sparse[0,3]).

In [5]:
import numpy as np
import scipy.sparse as scs

In [19]:
test_1d_sparse = scs.csr_matrix([[0],[1],[0]])
print 'Shape: ', test_1d_sparse.shape # expecting (3,1)
print 'NNZ: ', test_1d_sparse.nnz
print 'data: ', test_1d_sparse.data
print 'column indices: ', test_1d_sparse.indices
print 'indptr: ', test_1d_sparse.indptr # expecting [0,1,3]

Shape:  (3, 1)
NNZ:  1
data:  [1]
column indices:  [0]
indptr:  [0 0 1 1]


In [20]:
test_sparse = scs.csr_matrix([[1,2,0],[0,5,0],[7,0,0]])
print 'The type is: ', type(test_sparse)
print 'The shape: ', test_sparse.shape
print 'The # of non-zero elements is: ', test_sparse.nnz
print 'The non-zero elements are: ', test_sparse.data
print 'The indices of the columns are: ', test_sparse.indices
print 'The indices of the intptr are: ', test_sparse.indptr

The type is:  <class 'scipy.sparse.csr.csr_matrix'>
The shape:  (3, 3)
The # of non-zero elements is:  4
The non-zero elements are:  [1 2 5 7]
The indices of the columns are:  [0 1 1 0]
The indices of the intptr are:  [0 2 3 4]


In [21]:
test_total_sparse = scs.hstack((test_sparse, test_1d_sparse), format='csr')
test_total_sparse.A

array([[1, 2, 0, 0],
       [0, 5, 0, 1],
       [7, 0, 0, 0]])

In [4]:
print (np.hstack(np.array([[1,2,3,4,5],[2,4,6,8,10]])))
print (np.vstack(np.array([[1,2,3,4,5],[2,4,6,8,10]])))

[ 1  2  3  4  5  2  4  6  8 10]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


In [13]:
df_sparse[0,3]

1.0

In [8]:
print 'The non-zero elements are: ', df_sparse.data
print 'The indices of the columns are: ', df_sparse.indices
print 'The indices of the intptr are: ', df_sparse.indptr

The non-zero elements are:  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
The indices of the columns are:  [0 3 0 6 0 3 0 6 0 3 0 5 0 4 1 5 2 6 0 6 0 4 1 6 1 5 0 5 1 6 0 3 1 6 0 4 0
 3 0 3 2 3 0 3 0 4 1 6 0 6]
The indices of the intptr are:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


### Experimenting with Sparse encoding = True

In [26]:
vec = DictVectorizer(sparse=True)

In [27]:
df_sparse = vec.fit_transform(df[['e','f']].T.to_dict().values())
vec.get_feature_names()

['e=Boston',
 'e=Chicago',
 'e=New York',
 'f=Chrome',
 'f=Firefox',
 'f=Opera',
 'f=Safari']

In [28]:
print type(df_sparse)
print df_sparse.shape
print df_sparse
print df_sparse.A

<class 'scipy.sparse.csr.csr_matrix'>
(25, 7)
  (0, 1)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (1, 3)	1.0
  (2, 0)	1.0
  (2, 3)	1.0
  (3, 2)	1.0
  (3, 5)	1.0
  (4, 1)	1.0
  (4, 5)	1.0
  (5, 1)	1.0
  (5, 4)	1.0
  (6, 2)	1.0
  (6, 3)	1.0
  (7, 1)	1.0
  (7, 3)	1.0
  (8, 0)	1.0
  (8, 3)	1.0
  (9, 1)	1.0
  (9, 5)	1.0
  (10, 2)	1.0
  (10, 5)	1.0
  (11, 0)	1.0
  (11, 4)	1.0
  (12, 2)	1.0
  (12, 5)	1.0
  (13, 0)	1.0
  (13, 5)	1.0
  (14, 2)	1.0
  (14, 5)	1.0
  (15, 2)	1.0
  (15, 4)	1.0
  (16, 2)	1.0
  (16, 5)	1.0
  (17, 2)	1.0
  (17, 6)	1.0
  (18, 0)	1.0
  (18, 3)	1.0
  (19, 2)	1.0
  (19, 6)	1.0
  (20, 2)	1.0
  (20, 5)	1.0
  (21, 2)	1.0
  (21, 4)	1.0
  (22, 0)	1.0
  (22, 5)	1.0
  (23, 2)	1.0
  (23, 3)	1.0
  (24, 1)	1.0
  (24, 4)	1.0
[[ 0.  1.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  0.]
 [ 0.  1.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  1.  0.  0. 

In [23]:
print df[['e','f']]


           e        f
0    Chicago   Safari
1    Chicago    Opera
2   New York    Opera
3   New York   Safari
4   New York  Firefox
5    Chicago    Opera
6   New York   Safari
7    Chicago  Firefox
8     Boston  Firefox
9    Chicago   Safari
10  New York   Chrome
11   Chicago   Chrome
12   Chicago   Safari
13  New York  Firefox
14  New York   Chrome
15   Chicago    Opera
16  New York   Safari
17   Chicago   Chrome
18    Boston   Safari
19   Chicago  Firefox
20    Boston  Firefox
21   Chicago   Safari
22    Boston   Chrome
23  New York   Safari
24   Chicago    Opera


### Original with Sparse encoding = False

In [9]:
vec = DictVectorizer(sparse=False)
vec.fit_transform(df[['e', 'f']].T.to_dict().values())
vec.get_feature_names()

['e=Boston',
 'e=Chicago',
 'e=New York',
 'f=Chrome',
 'f=Firefox',
 'f=Opera',
 'f=Safari']

In [33]:
DictVectorizer(sparse=False).fit_transform(df[['e', 'f']].T.to_dict().values())[0]

array([ 1.,  0.,  0.,  0.,  0.,  1.,  0.])

In [3]:
df[['e', 'f']].T.to_dict()

{0: {'e': 'Boston', 'f': 'Safari'},
 1: {'e': 'New York', 'f': 'Firefox'},
 2: {'e': 'New York', 'f': 'Firefox'},
 3: {'e': 'Boston', 'f': 'Safari'},
 4: {'e': 'Boston', 'f': 'Safari'},
 5: {'e': 'Chicago', 'f': 'Firefox'},
 6: {'e': 'Boston', 'f': 'Opera'},
 7: {'e': 'Chicago', 'f': 'Safari'},
 8: {'e': 'Chicago', 'f': 'Chrome'},
 9: {'e': 'Boston', 'f': 'Safari'},
 10: {'e': 'New York', 'f': 'Firefox'},
 11: {'e': 'New York', 'f': 'Chrome'},
 12: {'e': 'New York', 'f': 'Chrome'},
 13: {'e': 'New York', 'f': 'Chrome'},
 14: {'e': 'Boston', 'f': 'Opera'},
 15: {'e': 'Boston', 'f': 'Safari'},
 16: {'e': 'New York', 'f': 'Safari'},
 17: {'e': 'Boston', 'f': 'Firefox'},
 18: {'e': 'Chicago', 'f': 'Chrome'},
 19: {'e': 'Boston', 'f': 'Opera'},
 20: {'e': 'Chicago', 'f': 'Opera'},
 21: {'e': 'Chicago', 'f': 'Firefox'},
 22: {'e': 'Boston', 'f': 'Opera'},
 23: {'e': 'Chicago', 'f': 'Firefox'},
 24: {'e': 'New York', 'f': 'Safari'}}

In [28]:
df[['e','f']].to_dict()

{'e': {0: 'Boston',
  1: 'Boston',
  2: 'New York',
  3: 'Chicago',
  4: 'Chicago',
  5: 'Boston',
  6: 'Boston',
  7: 'New York',
  8: 'Boston',
  9: 'New York',
  10: 'Chicago',
  11: 'Boston',
  12: 'New York',
  13: 'New York',
  14: 'New York',
  15: 'Boston',
  16: 'New York',
  17: 'New York',
  18: 'New York',
  19: 'Boston',
  20: 'Boston',
  21: 'New York',
  22: 'Chicago',
  23: 'Chicago',
  24: 'Chicago'},
 'f': {0: 'Opera',
  1: 'Safari',
  2: 'Firefox',
  3: 'Opera',
  4: 'Firefox',
  5: 'Opera',
  6: 'Safari',
  7: 'Firefox',
  8: 'Firefox',
  9: 'Chrome',
  10: 'Opera',
  11: 'Opera',
  12: 'Chrome',
  13: 'Chrome',
  14: 'Firefox',
  15: 'Chrome',
  16: 'Opera',
  17: 'Firefox',
  18: 'Safari',
  19: 'Safari',
  20: 'Chrome',
  21: 'Firefox',
  22: 'Chrome',
  23: 'Chrome',
  24: 'Safari'}}

### Let's figure out sparse. Helps with memory for encoding categorical features with a high rank

In [8]:
dfe_sparse,_,_ = one_hot_dataframe(df, ['e', 'f'], replace=True, sparse=True)
print dfe_sparse

           a         b         c  e=Boston  e=Chicago  e=New York  f=Chrome  \
0  -0.552624 -0.023072 -0.866505         0          1           0         0   
1  -1.646610 -0.715867  1.585951         0          0           1         1   
2   1.033257 -0.248838 -1.686223         0          1           0         1   
3   0.001851  0.525272 -1.867557         1          0           0         0   
4   0.057838  0.904903 -0.206544         0          1           0         1   
5  -0.658493  1.956263 -1.131318         1          0           0         0   
6   0.038234 -0.013313 -0.583437         1          0           0         0   
7   0.310459 -2.462892 -0.598408         0          1           0         0   
8  -0.293289  0.412152 -0.482514         0          0           1         0   
9   0.198823 -0.181557 -0.009523         0          1           0         0   
10  0.292240 -0.375509 -0.316093         1          0           0         0   
11  0.902264 -1.908472  0.216478         0          

In [15]:
dfe, _, _ = one_hot_dataframe(df, ['e', 'f'], replace=True)

In [16]:
print dfe

           a         b         c  e=Boston  e=Chicago  e=New York  f=Chrome  \
0  -0.239760 -0.574232 -0.595970         1          0           0         0   
1  -0.574809 -0.319168  0.479986         1          0           0         0   
2  -0.691434 -0.440980  0.870753         0          0           1         0   
3   0.585601  0.873340 -0.517539         0          1           0         0   
4  -0.202074 -0.343083 -1.181095         0          1           0         0   
5   0.149803  0.115482 -0.667478         1          0           0         0   
6   0.959770  0.602705  1.408899         1          0           0         0   
7   0.515406  1.183909 -2.472706         0          0           1         0   
8   0.125241 -2.100370 -1.034501         1          0           0         0   
9  -0.485841  0.288541 -0.242440         0          0           1         1   
10  0.866873 -0.486995 -1.176869         0          1           0         0   
11  1.141563 -0.052769 -0.002492         1          

In [6]:
print df

           a         b         c         e        f
0  -2.218027 -0.075260  0.536075   Chicago   Safari
1  -0.788003 -0.872123  2.198908    Boston   Safari
2   1.949646  2.097550 -0.029097  New York  Firefox
3  -0.181542 -2.069331 -2.318922  New York   Chrome
4  -1.018869  0.775520 -0.464508    Boston   Chrome
5   0.690170  1.026088 -2.682810    Boston   Safari
6   0.671896 -0.175252  0.407241  New York   Safari
7   0.770546  0.238234 -0.362008    Boston  Firefox
8  -1.049318 -0.403849  0.387242   Chicago    Opera
9  -0.606921 -0.332583 -1.648034  New York   Chrome
10  0.679687 -1.625962 -0.438157    Boston  Firefox
11  1.164254  0.105442  0.661446  New York  Firefox
12 -2.067548  1.252686  0.766033   Chicago   Safari
13  0.516288  0.296604  1.158520  New York   Chrome
14  0.885021 -1.347620  0.001952  New York    Opera
15  0.813130 -0.039354 -0.951146   Chicago   Chrome
16 -1.234355 -1.568677  0.178485  New York   Safari
17 -0.223021 -0.469136 -1.297888  New York   Chrome
18  0.501951

In [23]:
import pandas
import random
import numpy
from sklearn.feature_extraction import DictVectorizer

In [30]:
# Get a random DataFrame
df = pandas.DataFrame(numpy.random.randn(25, 3), columns=['a', 'b', 'c'])

# Make some random categorical columns
df['e'] = [random.choice(('Chicago', 'Boston', 'New York')) for i in range(df.shape[0])]
df['f'] = [random.choice(('Chrome', 'Firefox', 'Opera', "Safari")) for i in range(df.shape[0])]

### Scrap for new sparse ohe

In [ ]:
def ohe_dataframe_to_csr(data, cols, replace=True):
    """ Takes a dataframe and a list of columns that need to be encoded.
        Returns a 3-tuple comprising the data converted to csr matrix (csr), the vectorized data as csr,
        and the fitted vectorizor."""
    vec = DictVectorizer(sparse=False)
    vecData = vec.fit_transform(data[cols].T.to_dict().values())
    data_sparse = scipy.sparse.csr.matrix(data.as_matrix())

#### Working Alternative from [here](https://gist.github.com/saihttam/cad6d3d223fc8d769227)

In [31]:
def one_hot_dataframe(data, cols, replace=False, sparse=False):
    """ Takes a dataframe and a list of columns that need to be encoded.
        Returns a 3-tuple comprising the data, the vectorized data,
        and the fitted vectorizor."""
    vec = DictVectorizer(sparse=False)
    vecData = pandas.DataFrame(vec.fit_transform(data[cols].T.to_dict().values()))
    vecData.columns = vec.get_feature_names()
    vecData.index = data.index
    if replace is True:
        data = data.drop(cols, axis=1)
        data = data.join(vecData)
    return (data, vecData, vec)

Got original code from [here](https://gist.github.com/kljensen/5452382)

In [7]:
def one_hot_dataframe(data, cols, replace=True):
    """ Takes a dataframe and a list of columns that need to be encoded.
        Returns a 3-tuple comprising the data, the vectorized data,
        and the fitted vectorizor.
    """
    vec = DictVectorizer()
    mkdict = lambda row: dict((col, row[col]) for col in cols)
    vecData = pandas.DataFrame(vec.fit_transform(data[cols].apply(mkdict, axis=1)).toarray())
    vecData.columns = vec.get_feature_names()
    vecData.index = data.index
    if replace is True:
        data = data.drop(cols, axis=1)
        data = data.join(vecData)
    return (data, vecData, vec)